// Comprehensive dummy data organized by credential type

export const CREDENTIAL_TYPES = {
  employment: {
    name: "Employment Credential",
    fields: ["name", "jobTitle", "company", "department", "startDate", "salary"],
  },
  education: {
    name: "Education Credential",
    fields: ["name", "degree", "institution", "graduationDate", "major", "gpa"],
  },
  identity: {
    name: "Identity Credential",
    fields: ["name", "dateOfBirth", "nationality", "address", "idNumber", "issueDate"],
  },
  license: {
    name: "Professional License Credential",
    fields: ["name", "licenseType", "licenseNumber", "issuingAuthority", "issueDate", "expirationDate"],
  },
  membership: {
    name: "Membership Credential",
    fields: ["name", "organizationName", "membershipType", "membershipNumber", "joinDate", "membershipLevel"],
  },
}

export const DUMMY_DATA = {
  // Common fields
  names: [
    "Alice Johnson",
    "Bob Smith",
    "Carol Davis",
    "David Wilson",
    "Eva Brown",
    "Frank Miller",
    "Grace Lee",
    "Henry Taylor",
    "Iris Chen",
    "Jack Anderson",
    "Kate Thompson",
    "Liam Rodriguez",
    "Maya Patel",
    "Noah Williams",
    "Olivia Garcia",
    "Paul Martinez",
    "Quinn O'Connor",
    "Ruby Singh",
    "Sam Kim",
    "Tara Johnson",
    "Uma Sharma",
    "Victor Chang",
    "Wendy Foster",
    "Xavier Lopez",
    "Yuki Tanaka",
    "Zoe Mitchell",
    "Aaron Brooks",
    "Bella Cruz",
    "Carlos Mendez",
    "Diana Park",
  ],

  // Employment-specific
  jobTitles: [
    "Software Engineer",
    "Product Manager",
    "UX Designer",
    "Data Scientist",
    "DevOps Engineer",
    "Marketing Manager",
    "Sales Director",
    "HR Specialist",
    "Financial Analyst",
    "Project Manager",
    "Quality Assurance Engineer",
    "Business Analyst",
    "Technical Writer",
    "Customer Success Manager",
    "Operations Manager",
    "Security Engineer",
    "Mobile Developer",
    "Cloud Architect",
    "AI Researcher",
    "Blockchain Developer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Site Reliability Engineer",
    "Database Administrator",
    "Network Administrator",
    "Systems Analyst",
    "IT Consultant",
    "Cybersecurity Analyst",
    "Machine Learning Engineer",
  ],

  companies: [
    "TechCorp Inc",
    "InnovateLabs",
    "DataFlow Systems",
    "CloudFirst Solutions",
    "NextGen Technologies",
    "Digital Dynamics",
    "SmartSoft Ltd",
    "FutureTech",
    "CodeCraft Studios",
    "ByteWorks",
    "CyberSolutions",
    "AgileMinds",
    "TechPioneer",
    "DataVault Inc",
    "CloudNine Systems",
    "InnovateTech",
    "DigitalForge",
    "TechSphere",
    "CodeFactory",
    "DataBridge Corp",
    "StreamTech",
    "PixelPerfect",
    "LogicLabs",
    "NeuralNet Inc",
    "QuantumSoft",
    "BinaryBridge",
    "AlgoTech",
    "DevStream",
    "CloudCraft",
    "TechNova",
  ],

  departments: [
    "Engineering",
    "Product",
    "Design",
    "Data Science",
    "DevOps",
    "Marketing",
    "Sales",
    "Human Resources",
    "Finance",
    "Operations",
    "Quality Assurance",
    "Business Development",
    "Customer Support",
    "Research",
    "Security",
    "Mobile Development",
    "Cloud Infrastructure",
    "AI/ML",
    "Blockchain",
    "Platform",
    "Analytics",
    "Compliance",
    "Legal",
    "Strategy",
    "Innovation",
    "Partnerships",
    "Training",
    "Procurement",
    "Facilities",
    "Communications",
  ],

  salaries: [
    "65000",
    "72000",
    "85000",
    "95000",
    "110000",
    "125000",
    "140000",
    "155000",
    "170000",
    "185000",
    "58000",
    "68000",
    "78000",
    "88000",
    "98000",
    "108000",
    "118000",
    "128000",
    "138000",
    "148000",
    "75000",
    "82000",
    "92000",
    "102000",
    "112000",
    "122000",
    "132000",
    "142000",
    "152000",
    "162000",
  ],

  // Education-specific
  degrees: [
    "Bachelor of Science",
    "Master of Science",
    "Bachelor of Arts",
    "Master of Arts",
    "PhD",
    "Bachelor of Engineering",
    "Master of Engineering",
    "Bachelor of Computer Science",
    "Master of Computer Science",
    "MBA",
    "Bachelor of Mathematics",
    "Master of Mathematics",
    "Bachelor of Physics",
    "Master of Physics",
    "Bachelor of Chemistry",
    "Master of Chemistry",
    "Bachelor of Biology",
    "Master of Biology",
    "Bachelor of Economics",
    "Master of Economics",
    "Associate Degree",
    "Diploma",
    "Certificate",
    "Bachelor of Business",
    "Master of Business",
    "Bachelor of Psychology",
    "Master of Psychology",
    "Bachelor of Education",
    "Master of Education",
    "Juris Doctor",
  ],

  institutions: [
    "MIT",
    "Stanford University",
    "Harvard University",
    "UC Berkeley",
    "Carnegie Mellon",
    "Georgia Tech",
    "University of Washington",
    "Cornell University",
    "Princeton University",
    "Yale University",
    "Columbia University",
    "University of Chicago",
    "Northwestern University",
    "Duke University",
    "Rice University",
    "University of Pennsylvania",
    "Brown University",
    "Dartmouth College",
    "Vanderbilt University",
    "Emory University",
    "University of Michigan",
    "UCLA",
    "USC",
    "NYU",
    "Boston University",
    "University of Texas",
    "University of Florida",
    "Ohio State University",
    "Penn State",
    "University of Illinois",
  ],

  majors: [
    "Computer Science",
    "Software Engineering",
    "Data Science",
    "Artificial Intelligence",
    "Cybersecurity",
    "Information Systems",
    "Computer Engineering",
    "Electrical Engineering",
    "Mathematics",
    "Physics",
    "Chemistry",
    "Biology",
    "Economics",
    "Business Administration",
    "Marketing",
    "Finance",
    "Psychology",
    "Sociology",
    "Political Science",
    "Philosophy",
    "English Literature",
    "History",
    "Art",
    "Music",
    "Theater",
    "Mechanical Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Biomedical Engineering",
    "Environmental Science",
  ],

  gpas: [
    "3.2",
    "3.4",
    "3.5",
    "3.6",
    "3.7",
    "3.8",
    "3.9",
    "4.0",
    "3.3",
    "3.1",
    "2.9",
    "3.0",
    "3.25",
    "3.35",
    "3.45",
    "3.55",
    "3.65",
    "3.75",
    "3.85",
    "3.95",
    "2.8",
    "2.7",
    "3.15",
    "3.12",
    "3.18",
    "3.22",
    "3.28",
    "3.32",
    "3.38",
    "3.42",
  ],

  // Identity-specific
  nationalities: [
    "American",
    "Canadian",
    "British",
    "German",
    "French",
    "Italian",
    "Spanish",
    "Japanese",
    "Chinese",
    "Korean",
    "Indian",
    "Australian",
    "Brazilian",
    "Mexican",
    "Russian",
    "Dutch",
    "Swedish",
    "Norwegian",
    "Danish",
    "Finnish",
    "Swiss",
    "Austrian",
    "Belgian",
    "Portuguese",
    "Greek",
    "Turkish",
    "Israeli",
    "South African",
    "Egyptian",
    "Nigerian",
  ],

  addresses: [
    "123 Main St, New York, NY 10001",
    "456 Oak Ave, Los Angeles, CA 90210",
    "789 Pine Rd, Chicago, IL 60601",
    "321 Elm St, Houston, TX 77001",
    "654 Maple Dr, Phoenix, AZ 85001",
    "987 Cedar Ln, Philadelphia, PA 19101",
    "147 Birch Ct, San Antonio, TX 78201",
    "258 Spruce Way, San Diego, CA 92101",
    "369 Willow Pl, Dallas, TX 75201",
    "741 Aspen Blvd, San Jose, CA 95101",
    "852 Poplar St, Austin, TX 73301",
    "963 Hickory Ave, Jacksonville, FL 32201",
    "159 Walnut Dr, Fort Worth, TX 76101",
    "357 Chestnut Rd, Columbus, OH 43201",
    "486 Sycamore Ln, Charlotte, NC 28201",
    "624 Magnolia St, San Francisco, CA 94101",
    "735 Dogwood Ave, Indianapolis, IN 46201",
    "846 Redwood Dr, Seattle, WA 98101",
    "951 Cypress Ct, Denver, CO 80201",
    "162 Juniper Way, Washington, DC 20001",
    "273 Fir Pl, Boston, MA 02101",
    "384 Hemlock Blvd, El Paso, TX 79901",
    "495 Larch St, Detroit, MI 48201",
    "516 Beech Ave, Nashville, TN 37201",
    "627 Cottonwood Dr, Portland, OR 97201",
    "738 Basswood Rd, Oklahoma City, OK 73101",
    "849 Ironwood Ln, Las Vegas, NV 89101",
    "952 Mahogany Ct, Louisville, KY 40201",
    "163 Rosewood Way, Baltimore, MD 21201",
    "274 Sandalwood Pl, Milwaukee, WI 53201",
  ],

  idNumbers: [
    "ID123456789",
    "ID987654321",
    "ID456789123",
    "ID321654987",
    "ID789123456",
    "ID654987321",
    "ID147258369",
    "ID963852741",
    "ID258147369",
    "ID741963852",
    "ID369258147",
    "ID852741963",
    "ID159357486",
    "ID486159357",
    "ID357486159",
    "ID624135798",
    "ID798624135",
    "ID135798624",
    "ID246813579",
    "ID579246813",
    "ID813579246",
    "ID468135792",
    "ID792468135",
    "ID135792468",
    "ID357924681",
    "ID681357924",
    "ID924681357",
    "ID159486237",
    "ID237159486",
    "ID486237159",
  ],

  // License-specific
  licenseTypes: [
    "Software Development License",
    "Professional Engineer License",
    "Medical License",
    "Legal Practice License",
    "Teaching License",
    "Real Estate License",
    "Insurance License",
    "Financial Advisor License",
    "Contractor License",
    "Electrician License",
    "Plumber License",
    "Architect License",
    "Nurse License",
    "Pharmacist License",
    "Dentist License",
    "Veterinarian License",
    "Pilot License",
    "Driver License",
    "Commercial Driver License",
    "Motorcycle License",
    "Boat License",
    "Hunting License",
    "Fishing License",
    "Business License",
    "Food Handler License",
    "Alcohol Service License",
    "Security Guard License",
    "Private Investigator License",
    "Massage Therapist License",
    "Cosmetology License",
  ],

  licenseNumbers: [
    "LIC-2024-001234",
    "LIC-2024-005678",
    "LIC-2024-009012",
    "LIC-2024-003456",
    "LIC-2024-007890",
    "LIC-2023-012345",
    "LIC-2023-056789",
    "LIC-2023-090123",
    "LIC-2023-034567",
    "LIC-2023-078901",
    "LIC-2022-123456",
    "LIC-2022-567890",
    "LIC-2022-901234",
    "LIC-2022-345678",
    "LIC-2022-789012",
    "LIC-2021-234567",
    "LIC-2021-678901",
    "LIC-2021-012345",
    "LIC-2021-456789",
    "LIC-2021-890123",
    "LIC-2020-345678",
    "LIC-2020-789012",
    "LIC-2020-123456",
    "LIC-2020-567890",
    "LIC-2020-901234",
    "LIC-2019-456789",
    "LIC-2019-890123",
    "LIC-2019-234567",
    "LIC-2019-678901",
    "LIC-2019-012345",
  ],

  issuingAuthorities: [
    "State Board of Professional Engineers",
    "Department of Health",
    "State Bar Association",
    "Department of Education",
    "Real Estate Commission",
    "Insurance Department",
    "Financial Services Authority",
    "Contractor Licensing Board",
    "Electrical Board",
    "Plumbing Board",
    "Architecture Board",
    "Nursing Board",
    "Pharmacy Board",
    "Dental Board",
    "Veterinary Board",
    "Federal Aviation Administration",
    "Department of Motor Vehicles",
    "Commercial Vehicle Department",
    "Parks and Wildlife Department",
    "Business Licensing Office",
    "Health Department",
    "Alcohol Control Board",
    "Security Licensing Division",
    "Private Investigation Board",
    "Massage Therapy Board",
    "Cosmetology Board",
    "Professional Licensing Division",
    "Occupational Safety Board",
    "Environmental Protection Agency",
    "Fire Department",
  ],

  // Membership-specific
  organizationNames: [
    "IEEE Computer Society",
    "ACM",
    "Project Management Institute",
    "American Medical Association",
    "American Bar Association",
    "National Association of Realtors",
    "CPA Society",
    "Marketing Association",
    "HR Professional Society",
    "Engineering Society",
    "Data Science Association",
    "Cybersecurity Institute",
    "Software Development Guild",
    "Product Management Alliance",
    "UX Design Community",
    "Sales Professional Network",
    "Finance Professionals Group",
    "Operations Excellence Society",
    "Quality Assurance Institute",
    "Business Analysis Association",
    "Cloud Computing Consortium",
    "AI Research Society",
    "Blockchain Alliance",
    "Mobile Development Community",
    "Open Source Foundation",
    "Tech Leadership Forum",
    "Innovation Network",
    "Startup Founders Club",
    "Venture Capital Association",
    "Angel Investor Network",
  ],

  membershipTypes: [
    "Professional Member",
    "Associate Member",
    "Student Member",
    "Senior Member",
    "Fellow Member",
    "Honorary Member",
    "Life Member",
    "Corporate Member",
    "Individual Member",
    "Family Member",
    "Premium Member",
    "Basic Member",
    "Gold Member",
    "Silver Member",
    "Bronze Member",
    "Executive Member",
    "Regular Member",
    "Affiliate Member",
    "International Member",
    "Local Member",
    "Active Member",
    "Inactive Member",
    "Emeritus Member",
    "Charter Member",
    "Founding Member",
    "Sustaining Member",
    "Contributing Member",
    "Supporting Member",
    "Patron Member",
    "Benefactor Member",
  ],

  membershipNumbers: [
    "MEM-2024-001234",
    "MEM-2024-005678",
    "MEM-2024-009012",
    "MEM-2024-003456",
    "MEM-2024-007890",
    "MEM-2023-012345",
    "MEM-2023-056789",
    "MEM-2023-090123",
    "MEM-2023-034567",
    "MEM-2023-078901",
    "MEM-2022-123456",
    "MEM-2022-567890",
    "MEM-2022-901234",
    "MEM-2022-345678",
    "MEM-2022-789012",
    "MEM-2021-234567",
    "MEM-2021-678901",
    "MEM-2021-012345",
    "MEM-2021-456789",
    "MEM-2021-890123",
    "MEM-2020-345678",
    "MEM-2020-789012",
    "MEM-2020-123456",
    "MEM-2020-567890",
    "MEM-2020-901234",
    "MEM-2019-456789",
    "MEM-2019-890123",
    "MEM-2019-234567",
    "MEM-2019-678901",
    "MEM-2019-012345",
  ],

  membershipLevels: [
    "Level 1",
    "Level 2",
    "Level 3",
    "Level 4",
    "Level 5",
    "Bronze",
    "Silver",
    "Gold",
    "Platinum",
    "Diamond",
    "Basic",
    "Standard",
    "Premium",
    "Elite",
    "VIP",
    "Starter",
    "Professional",
    "Enterprise",
    "Ultimate",
    "Master",
    "Novice",
    "Intermediate",
    "Advanced",
    "Expert",
    "Guru",
    "Junior",
    "Senior",
    "Principal",
    "Distinguished",
    "Fellow",
  ],
}

// Helper function to generate dates
export function generateRandomDate(startYear: number, endYear: number): string {
  const start = new Date(startYear, 0, 1)
  const end = new Date(endYear, 11, 31)
  const randomTime = start.getTime() + Math.random() * (end.getTime() - start.getTime())
  return new Date(randomTime).toISOString().split("T")[0]
}

export function getRandomItem<T>(array: T[]): T {
  return array[Math.floor(Math.random() * array.length)]
}

export function getRandomItems<T>(array: T[], count: number): T[] {
  const shuffled = [...array].sort(() => 0.5 - Math.random())
  return shuffled.slice(0, count)
}
